baseurl = "https://linux-konsult.com"
title = "linux-konsult.com" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Tom" # Author's name.
    info = "Platform engineer with over 15 years experience in Linux systems and DevOps practices." # Author's job title or info.
    description = "linux-konsult.com" # Site description.
    keywords = "blog,devops,sustainability,esp8266,prometheus,grafana" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    #footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Contact details " # Add fixedbar content
    fixedbarContentAfter = "tom@linux-konsult.com" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    # enableTwitterShare = true
    # enableFacebookShare = true
    # enableHatenaShare = true
    # enableLineShare = true
    enableLinkedInShare = true

    thumbnail = "images/tn.png"

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/silverfisk/"


[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/tomeklof/"

# Menu links

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "Topics"
    weight = 2
    url  = "categories"
[[menu.main]]
    name = "Links"
    weight = 9
    url  = "links"
[[menu.main]]
    name = "Resume"
    weight = 10
    url = "https://whoami.linux-konsult.com"

# [markup.goldmark.renderer]
# unsafe = true
