baseurl = "https://silverfisk.github.io" # Hostname (and path) to the root.
title = "Toms personal page" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Tom" # Author's name.
    info = "Site Reliability Engineer" # Author's job title or info.
    description = "Toms personal website" # Site description.
    keywords = "blog,developer,esp8266,prometheus,grafana,bitcoin" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    # footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Want to send me a tip?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Now if there were just some kind of decentralized way of sending money..." # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    # enableTwitterShare = true
    # enableFacebookShare = true
    # enableHatenaShare = true
    # enableLineShare = true
    # enableLinkedInShare = true

    thumbnail = "images/tn.png"

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/silverfisk/"

# Menu links

[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "projects"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 10
    url = "about"

# [markup.goldmark.renderer]
# unsafe = true
